### PR TITLE
Add Navigation Stack to Stage Simulation

### LINKED ISSUE #20: Add a Local Planner
## Description
Currently the goal setting node `slam_mode_goal` publishes the `Twist` message that indicates the steering angle and velocity in the x-direction (forward/backward relative to the kart). 

This control data is set purely based on the position of the goal. In other words, it takes a straight-line path to the goal with some arbitrary velocity proportional to the distance the goal is from the robot. 

Instead, this goal should be processed by a local planner that finds a trajectory based on the goal, obstacles in the surrounding environment, and kinodynamic constraints of the kart (e.g.max velocity/acceleration).

## Sub-tasks
-[] ...

## Resources
* ...

### PR DESCRIPTION
**Pull request by zghera**
## What is a quick description of the change?
Add the ROS 2D navigation stack with `teb_local_planner` set as the local planner.

## Is this fixing an issue?
Closes #20

## Were any issues created as a result of this change?
#34 and #35

## Are there more details that are relevant?
Initially looked at just using `teb_local_planner` with the current ASSv2 architecture. However, teb's API is made to interface with move_base and we would end up having to reimplement a portion of `move_base`'s functionality to obtain the same `cmd_vel` topic that we need. Thus, it made sense to add move_base back.

With this change, the only major difference between the v2 and v1 architectures is the SLAM module (using rtabmap instead of hector_mapping).

## Check lists (check x in [ ] of list items)
For each of these items, please refer to the [software style guide](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv2/wiki/Software-Style-Guide)
- [ ] Test written/updated
- [ ] Tests passing
- [ ] Logging (where appropriate)
- [ ] Coding style

## Any additional comments?
Note: This was a huge PR. Not advisable for most other PRs. However, it was arguably appropriate in this case given the hefty requirements of move_base.

**RQT Graph**
move-base-stage-rqt

**Tf Tree**
move-base-stage-tf

### CODE REVIEW

**Review by Reschivon — APPROVED** [review]

**Review by alanssitis — CHANGES_REQUESTED** [review]
I  am currently encountering an issue where `amcl` and `map_server` are not being launched when running `roslaunch sim_stage stage.launch` . Currently trying to find the root of the issue. Also, you mixed tabs and spaces in `sim_stage/launch/stage.launch` ; there may be more since I haven't looked at other files that closely. Shouldn't be a big deal and could be automated in the future, so could be ignored for now and be dealt with in Issue #18 .

**Comment by zghera** [comment]
> I am currently encountering an issue where amcl and map_server are not being launched when running roslaunch sim_stage stage.launch . Currently trying to find the root of the issue. Also, you mixed tabs and spaces in sim_stage/launch/stage.launch ; there may be more since I haven't looked at other files that closely. Shouldn't be a big deal and could be automated in the future, so could be ignored for now and be dealt with in Issue https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv2/issues/18 .

Weird it is working on my local build. @Reschivon , did you try to run it?

I tried also running in docker using `amp-cli devel --build` but I am actually having an error when trying to `catkin_make`: 
```
$ amp-cli devel --build
Building containers...
Step 1/2: Building amp-devel:noetic-desktop.
 ---> Finished building amp-devel:noetic-desktop.
Step 2/2: Building amp-devel:frame-desktop.
 ---> Finished building amp-devel:frame-desktop.
Running amp-devel:frame-desktop...
Use [<Ctrl> + D] to stop and exit the container.
Entering container amp-assv2-scratch:d2837809cc.

root@ubuntu:/amp_ws# catkin_make
Base path: /amp_ws
Source space: /amp_ws/src
Build space: /amp_ws/build
Devel space: /amp_ws/devel
Install space: /amp_ws/install
####
#### Running command: "cmake /amp_ws/src -DCATKIN_DEVEL_PREFIX=/amp_ws/devel -DCMAKE_INSTALL_PREFIX=/amp_ws/install -G Unix Makefiles" in "/amp_ws/build"
####
CMake Error: The current CMakeCache.txt directory /amp_ws/build/CMakeCache.txt is different than the directory /home/z/Documents/AMP_ASSv2/build where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
CMake Error: The source "/amp_ws/src/CMakeLists.txt" does not match the source "/home/z/Documents/AMP_ASSv2/src/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
Invoking "cmake" failed
```

How did you test on this branch just now?

**Comment by alanssitis** [comment]
Via `amp-cli`, my comments above address the fix.

**Review by alanssitis — APPROVED** [review]
LGTM

**Pull request merged**
