### PR TITLE
"cone_finder" Package/Node

### PR DESCRIPTION
**Pull request by WDobert**
## What is a quick description of the change?
The obstacle pointcloud published by RTAB-Map is filtered and clustered to locate cone positions. These positions are published on the `/cone_finder/cones_found` topic. There is also a sub-node responsible for reading this topic and publishing data necessary to observe it in RViz.
## Is this fixing an issue?
#38
## Were any issues created as a result of this change?
No
## Are there more details that are relevant?
Further physical testing with actual cones should be carried out in order to verify and tune the functionality of this node. Specifically, the parameters for color filtering and clustering may need adjusting.
## Check lists (check x in [ ] of list items)
For each of these items, please refer to the [software style guide](https://github.com/Autonomous-Motorsports-Purdue/AMP_ASSv2/wiki/Software-Style-Guide)
- [ ] Test written/updated and implemented to CI
- [ ] Logging (where appropriate)

### CODE REVIEW

**Comment by alanssitis** [comment]
@WDobert It failed to build, check the error messages in "details" for the failed check.

**Comment by WDobert** [comment]
I don't think the error stems from anything we have control over?
image

**Review by alanssitis — APPROVED** [review]
LGTM! I am not so familiar with the `zed_host` package, so, before merging, make sure it is in fact correct. Not sure if this is supposed to happen, but the `SyncSource` parameter changed from `Camera` to an empty string.

**Comment by WDobert** [comment]
Made a quick fix to the RViz config, should now behave identically to how it was before.

**Pull request merged**
